CREATE DATABASE teamMain;
USE teamMain;

DESC user;
DESC subsuser;
DESC q_reply;

-- 외래키 찾는 쿼리
SELECT 
  TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME, REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME
FROM
  INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
  TABLE_SCHEMA = 'laundryService' AND
  TABLE_NAME = 'subsuser';

ALTER TABLE user
ADD COLUMN user_nickname varchar(45) UNIQUE NOT NULL;